# Makefile.in generated by automake 1.11 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009  Free Software Foundation,
# Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# Copyright 2011 University Corporation for Atmospheric Research
#
# This file is part of the Unidata NOAAPORT package.  See the file COPYRIGHT in
# the top-level source-directory of the package for copying and redistribution
# conditions.
#

################################################################################




pkgdatadir = $(datadir)/noaaport
pkgincludedir = $(includedir)/noaaport
pkglibdir = $(libdir)/noaaport
pkglibexecdir = $(libexecdir)/noaaport
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-linux-gnu
host_triplet = x86_64-unknown-linux-gnu
bin_PROGRAMS = dvbs_multicast$(EXEEXT) readnoaaport$(EXEEXT) \
	noaaportIngester$(EXEEXT)
subdir = .
DIST_COMMON = README $(am__configure_deps) $(dist_bin_SCRIPTS) \
	$(srcdir)/Makefile.am $(srcdir)/Makefile.in \
	$(srcdir)/config.h.in $(srcdir)/mainpage.h.in \
	$(top_srcdir)/configure compile config.guess config.sub \
	depcomp install-sh ltmain.sh missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES = mainpage.h
CONFIG_CLEAN_VPATH_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__installdirs = "$(DESTDIR)$(libdir)" "$(DESTDIR)$(bindir)" \
	"$(DESTDIR)$(bindir)"
LTLIBRARIES = $(lib_LTLIBRARIES)
libnoaaport_la_DEPENDENCIES = g2/lib.la gempak/lib.la libpng/libpng.la \
	zlib/lib.la
am_libnoaaport_la_OBJECTS = libnoaaport_la-shmfifo.lo
libnoaaport_la_OBJECTS = $(am_libnoaaport_la_OBJECTS)
PROGRAMS = $(bin_PROGRAMS)
am_dvbs_multicast_OBJECTS = dvbs_multicast.$(OBJEXT)
dvbs_multicast_OBJECTS = $(am_dvbs_multicast_OBJECTS)
dvbs_multicast_LDADD = $(LDADD)
dvbs_multicast_DEPENDENCIES = libnoaaport.la
am__objects_1 = noaaportIngester-grib2name.$(OBJEXT) \
	noaaportIngester-gribid.$(OBJEXT) \
	noaaportIngester-ldmProductQueue.$(OBJEXT) \
	noaaportIngester-png_io.$(OBJEXT) \
	noaaportIngester-process_prod.$(OBJEXT) \
	noaaportIngester-readpdb.$(OBJEXT) \
	noaaportIngester-readpdh.$(OBJEXT) \
	noaaportIngester-readpsh.$(OBJEXT) \
	noaaportIngester-readsbn.$(OBJEXT) \
	noaaportIngester-redbook_header.$(OBJEXT) \
	noaaportIngester-wgrib.$(OBJEXT) \
	noaaportIngester-wmo_header.$(OBJEXT)
am_noaaportIngester_OBJECTS =  \
	noaaportIngester-noaaportIngester.$(OBJEXT) $(am__objects_1) \
	noaaportIngester-fifo.$(OBJEXT) \
	noaaportIngester-fileReader.$(OBJEXT) \
	noaaportIngester-getFacilityName.$(OBJEXT) \
	noaaportIngester-multicastReader.$(OBJEXT) \
	noaaportIngester-productMaker.$(OBJEXT) \
	noaaportIngester-reader.$(OBJEXT)
noaaportIngester_OBJECTS = $(am_noaaportIngester_OBJECTS)
noaaportIngester_LDADD = $(LDADD)
noaaportIngester_DEPENDENCIES = libnoaaport.la
am__objects_2 = readnoaaport-grib2name.$(OBJEXT) \
	readnoaaport-gribid.$(OBJEXT) \
	readnoaaport-ldmProductQueue.$(OBJEXT) \
	readnoaaport-png_io.$(OBJEXT) \
	readnoaaport-process_prod.$(OBJEXT) \
	readnoaaport-readpdb.$(OBJEXT) readnoaaport-readpdh.$(OBJEXT) \
	readnoaaport-readpsh.$(OBJEXT) readnoaaport-readsbn.$(OBJEXT) \
	readnoaaport-redbook_header.$(OBJEXT) \
	readnoaaport-wgrib.$(OBJEXT) readnoaaport-wmo_header.$(OBJEXT)
am_readnoaaport_OBJECTS = readnoaaport-readnoaaport.$(OBJEXT) \
	$(am__objects_2)
readnoaaport_OBJECTS = $(am_readnoaaport_OBJECTS)
readnoaaport_LDADD = $(LDADD)
readnoaaport_DEPENDENCIES = libnoaaport.la
SCRIPTS = $(dist_bin_SCRIPTS)
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
SOURCES = $(libnoaaport_la_SOURCES) $(dvbs_multicast_SOURCES) \
	$(noaaportIngester_SOURCES) $(readnoaaport_SOURCES)
DIST_SOURCES = $(libnoaaport_la_SOURCES) $(dvbs_multicast_SOURCES) \
	$(noaaportIngester_SOURCES) $(readnoaaport_SOURCES)
RECURSIVE_TARGETS = all-recursive check-recursive dvi-recursive \
	html-recursive info-recursive install-data-recursive \
	install-dvi-recursive install-exec-recursive \
	install-html-recursive install-info-recursive \
	install-pdf-recursive install-ps-recursive install-recursive \
	installcheck-recursive installdirs-recursive pdf-recursive \
	ps-recursive uninstall-recursive
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
AM_RECURSIVE_TARGETS = $(RECURSIVE_TARGETS:-recursive=) \
	$(RECURSIVE_CLEAN_TARGETS:-recursive=) tags TAGS ctags CTAGS \
	distdir dist dist-all distcheck
ETAGS = etags
CTAGS = ctags
DIST_SUBDIRS = $(SUBDIRS)
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d "$(distdir)" \
    || { find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr "$(distdir)"; }; }
am__relativize = \
  dir0=`pwd`; \
  sed_first='s,^\([^/]*\)/.*$$,\1,'; \
  sed_rest='s,^[^/]*/*,,'; \
  sed_last='s,^.*/\([^/]*\)$$,\1,'; \
  sed_butlast='s,/*[^/]*$$,,'; \
  while test -n "$$dir1"; do \
    first=`echo "$$dir1" | sed -e "$$sed_first"`; \
    if test "$$first" != "."; then \
      if test "$$first" = ".."; then \
        dir2=`echo "$$dir0" | sed -e "$$sed_last"`/"$$dir2"; \
        dir0=`echo "$$dir0" | sed -e "$$sed_butlast"`; \
      else \
        first2=`echo "$$dir2" | sed -e "$$sed_first"`; \
        if test "$$first2" = "$$first"; then \
          dir2=`echo "$$dir2" | sed -e "$$sed_rest"`; \
        else \
          dir2="../$$dir2"; \
        fi; \
        dir0="$$dir0"/"$$first"; \
      fi; \
    fi; \
    dir1=`echo "$$dir1" | sed -e "$$sed_rest"`; \
  done; \
  reldir="$$dir2"
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /machine/steve/ldm/noaaport/missing --run aclocal-1.11
AMTAR = ${SHELL} /machine/steve/ldm/noaaport/missing --run tar
AR = ar
ARFLAGS = -cru
AUTOCONF = ${SHELL} /machine/steve/ldm/noaaport/missing --run autoconf
AUTOHEADER = ${SHELL} /machine/steve/ldm/noaaport/missing --run autoheader
AUTOMAKE = ${SHELL} /machine/steve/ldm/noaaport/missing --run automake-1.11
AWK = gawk
CC = c89
CCDEPMODE = depmode=gcc3
CFLAGS = -g -m64
CPP = c89 -E
CPPFLAGS = -I$(LDMHOME)/include -I$(LDMHOME)/src/ulog
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DSYMUTIL = 
ECHO = echo
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
F77 = gfortran
FFLAGS = -g -O2
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS =  -m64
LDMHOME = /machine/steve/ldm
LIBOBJS = 
LIBS = -lpthread 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /machine/steve/ldm/noaaport/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
NMEDIT = 
OBJEXT = o
PACKAGE = noaaport
PACKAGE_BUGREPORT = support-noaaport@unidata.ucar.edu
PACKAGE_NAME = NOAAPORT
PACKAGE_STRING = NOAAPORT 1.7.0.1
PACKAGE_TARNAME = noaaport
PACKAGE_VERSION = 1.7.0.1
PATH_SEPARATOR = :
RANLIB = ranlib
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/sh
STRIP = strip
SU = /bin/su
SUDO = 
VERSION = 1.7.0.1
abs_builddir = /machine/steve/ldm/noaaport
abs_srcdir = /machine/steve/ldm/noaaport
abs_top_builddir = /machine/steve/ldm/noaaport
abs_top_srcdir = /machine/steve/ldm/noaaport
ac_ct_CC = c89
ac_ct_CXX = g++
ac_ct_F77 = gfortran
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = x86_64-unknown-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = unknown
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-unknown-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /machine/steve/ldm/noaaport/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /machine/steve/ldm
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
subdirs =  libpng
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
LDMSRC = $(LDMHOME)/src
SUBDIRS = zlib g2 gempak libpng tables
distName = $(PACKAGE)-$(VERSION)
distArchive = $(distName).tar.gz
EXTRA_DIST = \
    	CHANGE_LOG \
    	COPYRIGHT \
	Doxyfile \
	html \
	mainpage.h \
	mainpage.h.in \
	nwstgdump.data

DISTCLEANFILES = mainpage.h $(distArchive)
lib_LTLIBRARIES = libnoaaport.la
libnoaaport_la_SOURCES = shmfifo.c shmfifo.h
libnoaaport_la_CPPFLAGS = \
	-I$(top_srcdir)/g2 \
	-I$(top_srcdir)/gempak \
	-I$(top_srcdir)/zlib

libnoaaport_la_LIBADD = g2/lib.la gempak/lib.la libpng/libpng.la zlib/lib.la
dist_bin_SCRIPTS = \
	dvbs_goes \
	dvbs_nwstg \
	dvbs_nwstg2 \
	dvbs_oconus \
	nplog_rotate

LDADD = libnoaaport.la -L$(LDMHOME)/lib -lldm -lxml2
dvbs_multicast_SOURCES = dvbs_multicast.c
COMMON_SOURCES = \
	dvbs.h \
	grib2name.c \
	gribid.c \
	ldmProductQueue.c ldmProductQueue.h \
	nport.h \
	png_io.c \
	process_prod.c \
	readpdb.c \
	readpdh.c \
	readpsh.c\
	readsbn.c \
	redbook_header.c \
	wgrib.c \
	wmo_header.c \
	wmo_header.h

COMMON_CPPFLAGS = \
	-I$(top_srcdir)/g2 -I$(top_srcdir)/gempak -I$(top_srcdir)/zlib

readnoaaport_SOURCES = readnoaaport.c $(COMMON_SOURCES)
readnoaaport_CPPFLAGS = $(COMMON_CPPFLAGS)
noaaportIngester_SOURCES = noaaportIngester.c $(COMMON_SOURCES) \
	fifo.c fifo.h \
	fileReader.c fileReader.h \
	getFacilityName.c getFacilityName.h \
	multicastReader.c multicastReader.h \
	productMaker.c productMaker.h \
	reader.c reader.h

noaaportIngester_CPPFLAGS = $(COMMON_CPPFLAGS)
TAGS_FILES = \
	*.c *.h \
	$(LDMSRC)/pq/*.c $(LDMSRC)/pq/*.h \
	$(LDMSRC)/protocol/*.c $(LDMSRC)/protocol/*.h \
	$(LDMSRC)/ulog/*.c $(LDMSRC)/ulog/*.h \
	$(LDMSRC)/misc/*.c $(LDMSRC)/misc/*.h \
	$(LDMSRC)/registry/*.c $(LDMSRC)/registry/*.h \
	$(LDMSRC)/rpc/*.c $(LDMSRC)/rpc/*.h

DISTCHECK_CONFIGURE_FLAGS = --disable-root-actions --disable-shared
FTPDIR = /web/ftp/pub/$(PACKAGE)
WEBROOT = /web/content/software/$(PACKAGE)
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-recursive

.SUFFIXES:
.SUFFIXES: .c .h .hin .i .lo .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@if test ! -f $@; then \
	  rm -f stamp-h1; \
	  $(MAKE) $(AM_MAKEFLAGS) stamp-h1; \
	else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
mainpage.h: $(top_builddir)/config.status $(srcdir)/mainpage.h.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	test -z "$(libdir)" || $(MKDIR_P) "$(DESTDIR)$(libdir)"
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	list2=; for p in $$list; do \
	  if test -f $$p; then \
	    list2="$$list2 $$p"; \
	  else :; fi; \
	done; \
	test -z "$$list2" || { \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 '$(DESTDIR)$(libdir)'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 "$(DESTDIR)$(libdir)"; \
	}

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	for p in $$list; do \
	  $(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(libdir)/$$f'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(libdir)/$$f"; \
	done

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  dir="`echo $$p | sed -e 's|/[^/]*$$||'`"; \
	  test "$$dir" != "$$p" || dir=.; \
	  echo "rm -f \"$${dir}/so_locations\""; \
	  rm -f "$${dir}/so_locations"; \
	done
libnoaaport.la: $(libnoaaport_la_OBJECTS) $(libnoaaport_la_DEPENDENCIES) 
	$(LINK) -rpath $(libdir) $(libnoaaport_la_OBJECTS) $(libnoaaport_la_LIBADD) $(LIBS)
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p || test -f $$p1; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	    echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	    $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	@list='$(bin_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list
dvbs_multicast$(EXEEXT): $(dvbs_multicast_OBJECTS) $(dvbs_multicast_DEPENDENCIES) 
	@rm -f dvbs_multicast$(EXEEXT)
	$(LINK) $(dvbs_multicast_OBJECTS) $(dvbs_multicast_LDADD) $(LIBS)
noaaportIngester$(EXEEXT): $(noaaportIngester_OBJECTS) $(noaaportIngester_DEPENDENCIES) 
	@rm -f noaaportIngester$(EXEEXT)
	$(LINK) $(noaaportIngester_OBJECTS) $(noaaportIngester_LDADD) $(LIBS)
readnoaaport$(EXEEXT): $(readnoaaport_OBJECTS) $(readnoaaport_DEPENDENCIES) 
	@rm -f readnoaaport$(EXEEXT)
	$(LINK) $(readnoaaport_OBJECTS) $(readnoaaport_LDADD) $(LIBS)
install-dist_binSCRIPTS: $(dist_bin_SCRIPTS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(dist_bin_SCRIPTS)'; test -n "$(bindir)" || list=; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  if test -f "$$d$$p"; then echo "$$d$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n' \
	    -e 'h;s|.*|.|' \
	    -e 'p;x;s,.*/,,;$(transform)' | sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1; } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) { files[d] = files[d] " " $$1; \
	      if (++n[d] == $(am__install_max)) { \
		print "f", d, files[d]; n[d] = 0; files[d] = "" } } \
	    else { print "f", d "/" $$4, $$1 } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	     if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	     test -z "$$files" || { \
	       echo " $(INSTALL_SCRIPT) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	       $(INSTALL_SCRIPT) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	     } \
	; done

uninstall-dist_binSCRIPTS:
	@$(NORMAL_UNINSTALL)
	@list='$(dist_bin_SCRIPTS)'; test -n "$(bindir)" || exit 0; \
	files=`for p in $$list; do echo "$$p"; done | \
	       sed -e 's,.*/,,;$(transform)'`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/dvbs_multicast.Po
include ./$(DEPDIR)/libnoaaport_la-shmfifo.Plo
include ./$(DEPDIR)/noaaportIngester-fifo.Po
include ./$(DEPDIR)/noaaportIngester-fileReader.Po
include ./$(DEPDIR)/noaaportIngester-getFacilityName.Po
include ./$(DEPDIR)/noaaportIngester-grib2name.Po
include ./$(DEPDIR)/noaaportIngester-gribid.Po
include ./$(DEPDIR)/noaaportIngester-ldmProductQueue.Po
include ./$(DEPDIR)/noaaportIngester-multicastReader.Po
include ./$(DEPDIR)/noaaportIngester-noaaportIngester.Po
include ./$(DEPDIR)/noaaportIngester-png_io.Po
include ./$(DEPDIR)/noaaportIngester-process_prod.Po
include ./$(DEPDIR)/noaaportIngester-productMaker.Po
include ./$(DEPDIR)/noaaportIngester-reader.Po
include ./$(DEPDIR)/noaaportIngester-readpdb.Po
include ./$(DEPDIR)/noaaportIngester-readpdh.Po
include ./$(DEPDIR)/noaaportIngester-readpsh.Po
include ./$(DEPDIR)/noaaportIngester-readsbn.Po
include ./$(DEPDIR)/noaaportIngester-redbook_header.Po
include ./$(DEPDIR)/noaaportIngester-wgrib.Po
include ./$(DEPDIR)/noaaportIngester-wmo_header.Po
include ./$(DEPDIR)/readnoaaport-grib2name.Po
include ./$(DEPDIR)/readnoaaport-gribid.Po
include ./$(DEPDIR)/readnoaaport-ldmProductQueue.Po
include ./$(DEPDIR)/readnoaaport-png_io.Po
include ./$(DEPDIR)/readnoaaport-process_prod.Po
include ./$(DEPDIR)/readnoaaport-readnoaaport.Po
include ./$(DEPDIR)/readnoaaport-readpdb.Po
include ./$(DEPDIR)/readnoaaport-readpdh.Po
include ./$(DEPDIR)/readnoaaport-readpsh.Po
include ./$(DEPDIR)/readnoaaport-readsbn.Po
include ./$(DEPDIR)/readnoaaport-redbook_header.Po
include ./$(DEPDIR)/readnoaaport-wgrib.Po
include ./$(DEPDIR)/readnoaaport-wmo_header.Po

.c.o:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c -o $@ $<

.c.obj:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.c.lo:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Plo
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LTCOMPILE) -c -o $@ $<

libnoaaport_la-shmfifo.lo: shmfifo.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libnoaaport_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libnoaaport_la-shmfifo.lo -MD -MP -MF $(DEPDIR)/libnoaaport_la-shmfifo.Tpo -c -o libnoaaport_la-shmfifo.lo `test -f 'shmfifo.c' || echo '$(srcdir)/'`shmfifo.c
	$(am__mv) $(DEPDIR)/libnoaaport_la-shmfifo.Tpo $(DEPDIR)/libnoaaport_la-shmfifo.Plo
#	source='shmfifo.c' object='libnoaaport_la-shmfifo.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libnoaaport_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libnoaaport_la-shmfifo.lo `test -f 'shmfifo.c' || echo '$(srcdir)/'`shmfifo.c

noaaportIngester-noaaportIngester.o: noaaportIngester.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-noaaportIngester.o -MD -MP -MF $(DEPDIR)/noaaportIngester-noaaportIngester.Tpo -c -o noaaportIngester-noaaportIngester.o `test -f 'noaaportIngester.c' || echo '$(srcdir)/'`noaaportIngester.c
	$(am__mv) $(DEPDIR)/noaaportIngester-noaaportIngester.Tpo $(DEPDIR)/noaaportIngester-noaaportIngester.Po
#	source='noaaportIngester.c' object='noaaportIngester-noaaportIngester.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-noaaportIngester.o `test -f 'noaaportIngester.c' || echo '$(srcdir)/'`noaaportIngester.c

noaaportIngester-noaaportIngester.obj: noaaportIngester.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-noaaportIngester.obj -MD -MP -MF $(DEPDIR)/noaaportIngester-noaaportIngester.Tpo -c -o noaaportIngester-noaaportIngester.obj `if test -f 'noaaportIngester.c'; then $(CYGPATH_W) 'noaaportIngester.c'; else $(CYGPATH_W) '$(srcdir)/noaaportIngester.c'; fi`
	$(am__mv) $(DEPDIR)/noaaportIngester-noaaportIngester.Tpo $(DEPDIR)/noaaportIngester-noaaportIngester.Po
#	source='noaaportIngester.c' object='noaaportIngester-noaaportIngester.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-noaaportIngester.obj `if test -f 'noaaportIngester.c'; then $(CYGPATH_W) 'noaaportIngester.c'; else $(CYGPATH_W) '$(srcdir)/noaaportIngester.c'; fi`

noaaportIngester-grib2name.o: grib2name.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-grib2name.o -MD -MP -MF $(DEPDIR)/noaaportIngester-grib2name.Tpo -c -o noaaportIngester-grib2name.o `test -f 'grib2name.c' || echo '$(srcdir)/'`grib2name.c
	$(am__mv) $(DEPDIR)/noaaportIngester-grib2name.Tpo $(DEPDIR)/noaaportIngester-grib2name.Po
#	source='grib2name.c' object='noaaportIngester-grib2name.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-grib2name.o `test -f 'grib2name.c' || echo '$(srcdir)/'`grib2name.c

noaaportIngester-grib2name.obj: grib2name.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-grib2name.obj -MD -MP -MF $(DEPDIR)/noaaportIngester-grib2name.Tpo -c -o noaaportIngester-grib2name.obj `if test -f 'grib2name.c'; then $(CYGPATH_W) 'grib2name.c'; else $(CYGPATH_W) '$(srcdir)/grib2name.c'; fi`
	$(am__mv) $(DEPDIR)/noaaportIngester-grib2name.Tpo $(DEPDIR)/noaaportIngester-grib2name.Po
#	source='grib2name.c' object='noaaportIngester-grib2name.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-grib2name.obj `if test -f 'grib2name.c'; then $(CYGPATH_W) 'grib2name.c'; else $(CYGPATH_W) '$(srcdir)/grib2name.c'; fi`

noaaportIngester-gribid.o: gribid.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-gribid.o -MD -MP -MF $(DEPDIR)/noaaportIngester-gribid.Tpo -c -o noaaportIngester-gribid.o `test -f 'gribid.c' || echo '$(srcdir)/'`gribid.c
	$(am__mv) $(DEPDIR)/noaaportIngester-gribid.Tpo $(DEPDIR)/noaaportIngester-gribid.Po
#	source='gribid.c' object='noaaportIngester-gribid.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-gribid.o `test -f 'gribid.c' || echo '$(srcdir)/'`gribid.c

noaaportIngester-gribid.obj: gribid.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-gribid.obj -MD -MP -MF $(DEPDIR)/noaaportIngester-gribid.Tpo -c -o noaaportIngester-gribid.obj `if test -f 'gribid.c'; then $(CYGPATH_W) 'gribid.c'; else $(CYGPATH_W) '$(srcdir)/gribid.c'; fi`
	$(am__mv) $(DEPDIR)/noaaportIngester-gribid.Tpo $(DEPDIR)/noaaportIngester-gribid.Po
#	source='gribid.c' object='noaaportIngester-gribid.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-gribid.obj `if test -f 'gribid.c'; then $(CYGPATH_W) 'gribid.c'; else $(CYGPATH_W) '$(srcdir)/gribid.c'; fi`

noaaportIngester-ldmProductQueue.o: ldmProductQueue.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-ldmProductQueue.o -MD -MP -MF $(DEPDIR)/noaaportIngester-ldmProductQueue.Tpo -c -o noaaportIngester-ldmProductQueue.o `test -f 'ldmProductQueue.c' || echo '$(srcdir)/'`ldmProductQueue.c
	$(am__mv) $(DEPDIR)/noaaportIngester-ldmProductQueue.Tpo $(DEPDIR)/noaaportIngester-ldmProductQueue.Po
#	source='ldmProductQueue.c' object='noaaportIngester-ldmProductQueue.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-ldmProductQueue.o `test -f 'ldmProductQueue.c' || echo '$(srcdir)/'`ldmProductQueue.c

noaaportIngester-ldmProductQueue.obj: ldmProductQueue.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-ldmProductQueue.obj -MD -MP -MF $(DEPDIR)/noaaportIngester-ldmProductQueue.Tpo -c -o noaaportIngester-ldmProductQueue.obj `if test -f 'ldmProductQueue.c'; then $(CYGPATH_W) 'ldmProductQueue.c'; else $(CYGPATH_W) '$(srcdir)/ldmProductQueue.c'; fi`
	$(am__mv) $(DEPDIR)/noaaportIngester-ldmProductQueue.Tpo $(DEPDIR)/noaaportIngester-ldmProductQueue.Po
#	source='ldmProductQueue.c' object='noaaportIngester-ldmProductQueue.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-ldmProductQueue.obj `if test -f 'ldmProductQueue.c'; then $(CYGPATH_W) 'ldmProductQueue.c'; else $(CYGPATH_W) '$(srcdir)/ldmProductQueue.c'; fi`

noaaportIngester-png_io.o: png_io.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-png_io.o -MD -MP -MF $(DEPDIR)/noaaportIngester-png_io.Tpo -c -o noaaportIngester-png_io.o `test -f 'png_io.c' || echo '$(srcdir)/'`png_io.c
	$(am__mv) $(DEPDIR)/noaaportIngester-png_io.Tpo $(DEPDIR)/noaaportIngester-png_io.Po
#	source='png_io.c' object='noaaportIngester-png_io.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-png_io.o `test -f 'png_io.c' || echo '$(srcdir)/'`png_io.c

noaaportIngester-png_io.obj: png_io.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-png_io.obj -MD -MP -MF $(DEPDIR)/noaaportIngester-png_io.Tpo -c -o noaaportIngester-png_io.obj `if test -f 'png_io.c'; then $(CYGPATH_W) 'png_io.c'; else $(CYGPATH_W) '$(srcdir)/png_io.c'; fi`
	$(am__mv) $(DEPDIR)/noaaportIngester-png_io.Tpo $(DEPDIR)/noaaportIngester-png_io.Po
#	source='png_io.c' object='noaaportIngester-png_io.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-png_io.obj `if test -f 'png_io.c'; then $(CYGPATH_W) 'png_io.c'; else $(CYGPATH_W) '$(srcdir)/png_io.c'; fi`

noaaportIngester-process_prod.o: process_prod.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-process_prod.o -MD -MP -MF $(DEPDIR)/noaaportIngester-process_prod.Tpo -c -o noaaportIngester-process_prod.o `test -f 'process_prod.c' || echo '$(srcdir)/'`process_prod.c
	$(am__mv) $(DEPDIR)/noaaportIngester-process_prod.Tpo $(DEPDIR)/noaaportIngester-process_prod.Po
#	source='process_prod.c' object='noaaportIngester-process_prod.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-process_prod.o `test -f 'process_prod.c' || echo '$(srcdir)/'`process_prod.c

noaaportIngester-process_prod.obj: process_prod.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-process_prod.obj -MD -MP -MF $(DEPDIR)/noaaportIngester-process_prod.Tpo -c -o noaaportIngester-process_prod.obj `if test -f 'process_prod.c'; then $(CYGPATH_W) 'process_prod.c'; else $(CYGPATH_W) '$(srcdir)/process_prod.c'; fi`
	$(am__mv) $(DEPDIR)/noaaportIngester-process_prod.Tpo $(DEPDIR)/noaaportIngester-process_prod.Po
#	source='process_prod.c' object='noaaportIngester-process_prod.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-process_prod.obj `if test -f 'process_prod.c'; then $(CYGPATH_W) 'process_prod.c'; else $(CYGPATH_W) '$(srcdir)/process_prod.c'; fi`

noaaportIngester-readpdb.o: readpdb.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-readpdb.o -MD -MP -MF $(DEPDIR)/noaaportIngester-readpdb.Tpo -c -o noaaportIngester-readpdb.o `test -f 'readpdb.c' || echo '$(srcdir)/'`readpdb.c
	$(am__mv) $(DEPDIR)/noaaportIngester-readpdb.Tpo $(DEPDIR)/noaaportIngester-readpdb.Po
#	source='readpdb.c' object='noaaportIngester-readpdb.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-readpdb.o `test -f 'readpdb.c' || echo '$(srcdir)/'`readpdb.c

noaaportIngester-readpdb.obj: readpdb.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-readpdb.obj -MD -MP -MF $(DEPDIR)/noaaportIngester-readpdb.Tpo -c -o noaaportIngester-readpdb.obj `if test -f 'readpdb.c'; then $(CYGPATH_W) 'readpdb.c'; else $(CYGPATH_W) '$(srcdir)/readpdb.c'; fi`
	$(am__mv) $(DEPDIR)/noaaportIngester-readpdb.Tpo $(DEPDIR)/noaaportIngester-readpdb.Po
#	source='readpdb.c' object='noaaportIngester-readpdb.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-readpdb.obj `if test -f 'readpdb.c'; then $(CYGPATH_W) 'readpdb.c'; else $(CYGPATH_W) '$(srcdir)/readpdb.c'; fi`

noaaportIngester-readpdh.o: readpdh.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-readpdh.o -MD -MP -MF $(DEPDIR)/noaaportIngester-readpdh.Tpo -c -o noaaportIngester-readpdh.o `test -f 'readpdh.c' || echo '$(srcdir)/'`readpdh.c
	$(am__mv) $(DEPDIR)/noaaportIngester-readpdh.Tpo $(DEPDIR)/noaaportIngester-readpdh.Po
#	source='readpdh.c' object='noaaportIngester-readpdh.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-readpdh.o `test -f 'readpdh.c' || echo '$(srcdir)/'`readpdh.c

noaaportIngester-readpdh.obj: readpdh.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-readpdh.obj -MD -MP -MF $(DEPDIR)/noaaportIngester-readpdh.Tpo -c -o noaaportIngester-readpdh.obj `if test -f 'readpdh.c'; then $(CYGPATH_W) 'readpdh.c'; else $(CYGPATH_W) '$(srcdir)/readpdh.c'; fi`
	$(am__mv) $(DEPDIR)/noaaportIngester-readpdh.Tpo $(DEPDIR)/noaaportIngester-readpdh.Po
#	source='readpdh.c' object='noaaportIngester-readpdh.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-readpdh.obj `if test -f 'readpdh.c'; then $(CYGPATH_W) 'readpdh.c'; else $(CYGPATH_W) '$(srcdir)/readpdh.c'; fi`

noaaportIngester-readpsh.o: readpsh.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-readpsh.o -MD -MP -MF $(DEPDIR)/noaaportIngester-readpsh.Tpo -c -o noaaportIngester-readpsh.o `test -f 'readpsh.c' || echo '$(srcdir)/'`readpsh.c
	$(am__mv) $(DEPDIR)/noaaportIngester-readpsh.Tpo $(DEPDIR)/noaaportIngester-readpsh.Po
#	source='readpsh.c' object='noaaportIngester-readpsh.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-readpsh.o `test -f 'readpsh.c' || echo '$(srcdir)/'`readpsh.c

noaaportIngester-readpsh.obj: readpsh.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-readpsh.obj -MD -MP -MF $(DEPDIR)/noaaportIngester-readpsh.Tpo -c -o noaaportIngester-readpsh.obj `if test -f 'readpsh.c'; then $(CYGPATH_W) 'readpsh.c'; else $(CYGPATH_W) '$(srcdir)/readpsh.c'; fi`
	$(am__mv) $(DEPDIR)/noaaportIngester-readpsh.Tpo $(DEPDIR)/noaaportIngester-readpsh.Po
#	source='readpsh.c' object='noaaportIngester-readpsh.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-readpsh.obj `if test -f 'readpsh.c'; then $(CYGPATH_W) 'readpsh.c'; else $(CYGPATH_W) '$(srcdir)/readpsh.c'; fi`

noaaportIngester-readsbn.o: readsbn.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-readsbn.o -MD -MP -MF $(DEPDIR)/noaaportIngester-readsbn.Tpo -c -o noaaportIngester-readsbn.o `test -f 'readsbn.c' || echo '$(srcdir)/'`readsbn.c
	$(am__mv) $(DEPDIR)/noaaportIngester-readsbn.Tpo $(DEPDIR)/noaaportIngester-readsbn.Po
#	source='readsbn.c' object='noaaportIngester-readsbn.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-readsbn.o `test -f 'readsbn.c' || echo '$(srcdir)/'`readsbn.c

noaaportIngester-readsbn.obj: readsbn.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-readsbn.obj -MD -MP -MF $(DEPDIR)/noaaportIngester-readsbn.Tpo -c -o noaaportIngester-readsbn.obj `if test -f 'readsbn.c'; then $(CYGPATH_W) 'readsbn.c'; else $(CYGPATH_W) '$(srcdir)/readsbn.c'; fi`
	$(am__mv) $(DEPDIR)/noaaportIngester-readsbn.Tpo $(DEPDIR)/noaaportIngester-readsbn.Po
#	source='readsbn.c' object='noaaportIngester-readsbn.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-readsbn.obj `if test -f 'readsbn.c'; then $(CYGPATH_W) 'readsbn.c'; else $(CYGPATH_W) '$(srcdir)/readsbn.c'; fi`

noaaportIngester-redbook_header.o: redbook_header.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-redbook_header.o -MD -MP -MF $(DEPDIR)/noaaportIngester-redbook_header.Tpo -c -o noaaportIngester-redbook_header.o `test -f 'redbook_header.c' || echo '$(srcdir)/'`redbook_header.c
	$(am__mv) $(DEPDIR)/noaaportIngester-redbook_header.Tpo $(DEPDIR)/noaaportIngester-redbook_header.Po
#	source='redbook_header.c' object='noaaportIngester-redbook_header.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-redbook_header.o `test -f 'redbook_header.c' || echo '$(srcdir)/'`redbook_header.c

noaaportIngester-redbook_header.obj: redbook_header.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-redbook_header.obj -MD -MP -MF $(DEPDIR)/noaaportIngester-redbook_header.Tpo -c -o noaaportIngester-redbook_header.obj `if test -f 'redbook_header.c'; then $(CYGPATH_W) 'redbook_header.c'; else $(CYGPATH_W) '$(srcdir)/redbook_header.c'; fi`
	$(am__mv) $(DEPDIR)/noaaportIngester-redbook_header.Tpo $(DEPDIR)/noaaportIngester-redbook_header.Po
#	source='redbook_header.c' object='noaaportIngester-redbook_header.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-redbook_header.obj `if test -f 'redbook_header.c'; then $(CYGPATH_W) 'redbook_header.c'; else $(CYGPATH_W) '$(srcdir)/redbook_header.c'; fi`

noaaportIngester-wgrib.o: wgrib.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-wgrib.o -MD -MP -MF $(DEPDIR)/noaaportIngester-wgrib.Tpo -c -o noaaportIngester-wgrib.o `test -f 'wgrib.c' || echo '$(srcdir)/'`wgrib.c
	$(am__mv) $(DEPDIR)/noaaportIngester-wgrib.Tpo $(DEPDIR)/noaaportIngester-wgrib.Po
#	source='wgrib.c' object='noaaportIngester-wgrib.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-wgrib.o `test -f 'wgrib.c' || echo '$(srcdir)/'`wgrib.c

noaaportIngester-wgrib.obj: wgrib.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-wgrib.obj -MD -MP -MF $(DEPDIR)/noaaportIngester-wgrib.Tpo -c -o noaaportIngester-wgrib.obj `if test -f 'wgrib.c'; then $(CYGPATH_W) 'wgrib.c'; else $(CYGPATH_W) '$(srcdir)/wgrib.c'; fi`
	$(am__mv) $(DEPDIR)/noaaportIngester-wgrib.Tpo $(DEPDIR)/noaaportIngester-wgrib.Po
#	source='wgrib.c' object='noaaportIngester-wgrib.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-wgrib.obj `if test -f 'wgrib.c'; then $(CYGPATH_W) 'wgrib.c'; else $(CYGPATH_W) '$(srcdir)/wgrib.c'; fi`

noaaportIngester-wmo_header.o: wmo_header.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-wmo_header.o -MD -MP -MF $(DEPDIR)/noaaportIngester-wmo_header.Tpo -c -o noaaportIngester-wmo_header.o `test -f 'wmo_header.c' || echo '$(srcdir)/'`wmo_header.c
	$(am__mv) $(DEPDIR)/noaaportIngester-wmo_header.Tpo $(DEPDIR)/noaaportIngester-wmo_header.Po
#	source='wmo_header.c' object='noaaportIngester-wmo_header.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-wmo_header.o `test -f 'wmo_header.c' || echo '$(srcdir)/'`wmo_header.c

noaaportIngester-wmo_header.obj: wmo_header.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-wmo_header.obj -MD -MP -MF $(DEPDIR)/noaaportIngester-wmo_header.Tpo -c -o noaaportIngester-wmo_header.obj `if test -f 'wmo_header.c'; then $(CYGPATH_W) 'wmo_header.c'; else $(CYGPATH_W) '$(srcdir)/wmo_header.c'; fi`
	$(am__mv) $(DEPDIR)/noaaportIngester-wmo_header.Tpo $(DEPDIR)/noaaportIngester-wmo_header.Po
#	source='wmo_header.c' object='noaaportIngester-wmo_header.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-wmo_header.obj `if test -f 'wmo_header.c'; then $(CYGPATH_W) 'wmo_header.c'; else $(CYGPATH_W) '$(srcdir)/wmo_header.c'; fi`

noaaportIngester-fifo.o: fifo.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-fifo.o -MD -MP -MF $(DEPDIR)/noaaportIngester-fifo.Tpo -c -o noaaportIngester-fifo.o `test -f 'fifo.c' || echo '$(srcdir)/'`fifo.c
	$(am__mv) $(DEPDIR)/noaaportIngester-fifo.Tpo $(DEPDIR)/noaaportIngester-fifo.Po
#	source='fifo.c' object='noaaportIngester-fifo.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-fifo.o `test -f 'fifo.c' || echo '$(srcdir)/'`fifo.c

noaaportIngester-fifo.obj: fifo.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-fifo.obj -MD -MP -MF $(DEPDIR)/noaaportIngester-fifo.Tpo -c -o noaaportIngester-fifo.obj `if test -f 'fifo.c'; then $(CYGPATH_W) 'fifo.c'; else $(CYGPATH_W) '$(srcdir)/fifo.c'; fi`
	$(am__mv) $(DEPDIR)/noaaportIngester-fifo.Tpo $(DEPDIR)/noaaportIngester-fifo.Po
#	source='fifo.c' object='noaaportIngester-fifo.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-fifo.obj `if test -f 'fifo.c'; then $(CYGPATH_W) 'fifo.c'; else $(CYGPATH_W) '$(srcdir)/fifo.c'; fi`

noaaportIngester-fileReader.o: fileReader.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-fileReader.o -MD -MP -MF $(DEPDIR)/noaaportIngester-fileReader.Tpo -c -o noaaportIngester-fileReader.o `test -f 'fileReader.c' || echo '$(srcdir)/'`fileReader.c
	$(am__mv) $(DEPDIR)/noaaportIngester-fileReader.Tpo $(DEPDIR)/noaaportIngester-fileReader.Po
#	source='fileReader.c' object='noaaportIngester-fileReader.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-fileReader.o `test -f 'fileReader.c' || echo '$(srcdir)/'`fileReader.c

noaaportIngester-fileReader.obj: fileReader.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-fileReader.obj -MD -MP -MF $(DEPDIR)/noaaportIngester-fileReader.Tpo -c -o noaaportIngester-fileReader.obj `if test -f 'fileReader.c'; then $(CYGPATH_W) 'fileReader.c'; else $(CYGPATH_W) '$(srcdir)/fileReader.c'; fi`
	$(am__mv) $(DEPDIR)/noaaportIngester-fileReader.Tpo $(DEPDIR)/noaaportIngester-fileReader.Po
#	source='fileReader.c' object='noaaportIngester-fileReader.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-fileReader.obj `if test -f 'fileReader.c'; then $(CYGPATH_W) 'fileReader.c'; else $(CYGPATH_W) '$(srcdir)/fileReader.c'; fi`

noaaportIngester-getFacilityName.o: getFacilityName.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-getFacilityName.o -MD -MP -MF $(DEPDIR)/noaaportIngester-getFacilityName.Tpo -c -o noaaportIngester-getFacilityName.o `test -f 'getFacilityName.c' || echo '$(srcdir)/'`getFacilityName.c
	$(am__mv) $(DEPDIR)/noaaportIngester-getFacilityName.Tpo $(DEPDIR)/noaaportIngester-getFacilityName.Po
#	source='getFacilityName.c' object='noaaportIngester-getFacilityName.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-getFacilityName.o `test -f 'getFacilityName.c' || echo '$(srcdir)/'`getFacilityName.c

noaaportIngester-getFacilityName.obj: getFacilityName.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-getFacilityName.obj -MD -MP -MF $(DEPDIR)/noaaportIngester-getFacilityName.Tpo -c -o noaaportIngester-getFacilityName.obj `if test -f 'getFacilityName.c'; then $(CYGPATH_W) 'getFacilityName.c'; else $(CYGPATH_W) '$(srcdir)/getFacilityName.c'; fi`
	$(am__mv) $(DEPDIR)/noaaportIngester-getFacilityName.Tpo $(DEPDIR)/noaaportIngester-getFacilityName.Po
#	source='getFacilityName.c' object='noaaportIngester-getFacilityName.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-getFacilityName.obj `if test -f 'getFacilityName.c'; then $(CYGPATH_W) 'getFacilityName.c'; else $(CYGPATH_W) '$(srcdir)/getFacilityName.c'; fi`

noaaportIngester-multicastReader.o: multicastReader.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-multicastReader.o -MD -MP -MF $(DEPDIR)/noaaportIngester-multicastReader.Tpo -c -o noaaportIngester-multicastReader.o `test -f 'multicastReader.c' || echo '$(srcdir)/'`multicastReader.c
	$(am__mv) $(DEPDIR)/noaaportIngester-multicastReader.Tpo $(DEPDIR)/noaaportIngester-multicastReader.Po
#	source='multicastReader.c' object='noaaportIngester-multicastReader.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-multicastReader.o `test -f 'multicastReader.c' || echo '$(srcdir)/'`multicastReader.c

noaaportIngester-multicastReader.obj: multicastReader.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-multicastReader.obj -MD -MP -MF $(DEPDIR)/noaaportIngester-multicastReader.Tpo -c -o noaaportIngester-multicastReader.obj `if test -f 'multicastReader.c'; then $(CYGPATH_W) 'multicastReader.c'; else $(CYGPATH_W) '$(srcdir)/multicastReader.c'; fi`
	$(am__mv) $(DEPDIR)/noaaportIngester-multicastReader.Tpo $(DEPDIR)/noaaportIngester-multicastReader.Po
#	source='multicastReader.c' object='noaaportIngester-multicastReader.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-multicastReader.obj `if test -f 'multicastReader.c'; then $(CYGPATH_W) 'multicastReader.c'; else $(CYGPATH_W) '$(srcdir)/multicastReader.c'; fi`

noaaportIngester-productMaker.o: productMaker.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-productMaker.o -MD -MP -MF $(DEPDIR)/noaaportIngester-productMaker.Tpo -c -o noaaportIngester-productMaker.o `test -f 'productMaker.c' || echo '$(srcdir)/'`productMaker.c
	$(am__mv) $(DEPDIR)/noaaportIngester-productMaker.Tpo $(DEPDIR)/noaaportIngester-productMaker.Po
#	source='productMaker.c' object='noaaportIngester-productMaker.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-productMaker.o `test -f 'productMaker.c' || echo '$(srcdir)/'`productMaker.c

noaaportIngester-productMaker.obj: productMaker.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-productMaker.obj -MD -MP -MF $(DEPDIR)/noaaportIngester-productMaker.Tpo -c -o noaaportIngester-productMaker.obj `if test -f 'productMaker.c'; then $(CYGPATH_W) 'productMaker.c'; else $(CYGPATH_W) '$(srcdir)/productMaker.c'; fi`
	$(am__mv) $(DEPDIR)/noaaportIngester-productMaker.Tpo $(DEPDIR)/noaaportIngester-productMaker.Po
#	source='productMaker.c' object='noaaportIngester-productMaker.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-productMaker.obj `if test -f 'productMaker.c'; then $(CYGPATH_W) 'productMaker.c'; else $(CYGPATH_W) '$(srcdir)/productMaker.c'; fi`

noaaportIngester-reader.o: reader.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-reader.o -MD -MP -MF $(DEPDIR)/noaaportIngester-reader.Tpo -c -o noaaportIngester-reader.o `test -f 'reader.c' || echo '$(srcdir)/'`reader.c
	$(am__mv) $(DEPDIR)/noaaportIngester-reader.Tpo $(DEPDIR)/noaaportIngester-reader.Po
#	source='reader.c' object='noaaportIngester-reader.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-reader.o `test -f 'reader.c' || echo '$(srcdir)/'`reader.c

noaaportIngester-reader.obj: reader.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT noaaportIngester-reader.obj -MD -MP -MF $(DEPDIR)/noaaportIngester-reader.Tpo -c -o noaaportIngester-reader.obj `if test -f 'reader.c'; then $(CYGPATH_W) 'reader.c'; else $(CYGPATH_W) '$(srcdir)/reader.c'; fi`
	$(am__mv) $(DEPDIR)/noaaportIngester-reader.Tpo $(DEPDIR)/noaaportIngester-reader.Po
#	source='reader.c' object='noaaportIngester-reader.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(noaaportIngester_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o noaaportIngester-reader.obj `if test -f 'reader.c'; then $(CYGPATH_W) 'reader.c'; else $(CYGPATH_W) '$(srcdir)/reader.c'; fi`

readnoaaport-readnoaaport.o: readnoaaport.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT readnoaaport-readnoaaport.o -MD -MP -MF $(DEPDIR)/readnoaaport-readnoaaport.Tpo -c -o readnoaaport-readnoaaport.o `test -f 'readnoaaport.c' || echo '$(srcdir)/'`readnoaaport.c
	$(am__mv) $(DEPDIR)/readnoaaport-readnoaaport.Tpo $(DEPDIR)/readnoaaport-readnoaaport.Po
#	source='readnoaaport.c' object='readnoaaport-readnoaaport.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o readnoaaport-readnoaaport.o `test -f 'readnoaaport.c' || echo '$(srcdir)/'`readnoaaport.c

readnoaaport-readnoaaport.obj: readnoaaport.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT readnoaaport-readnoaaport.obj -MD -MP -MF $(DEPDIR)/readnoaaport-readnoaaport.Tpo -c -o readnoaaport-readnoaaport.obj `if test -f 'readnoaaport.c'; then $(CYGPATH_W) 'readnoaaport.c'; else $(CYGPATH_W) '$(srcdir)/readnoaaport.c'; fi`
	$(am__mv) $(DEPDIR)/readnoaaport-readnoaaport.Tpo $(DEPDIR)/readnoaaport-readnoaaport.Po
#	source='readnoaaport.c' object='readnoaaport-readnoaaport.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o readnoaaport-readnoaaport.obj `if test -f 'readnoaaport.c'; then $(CYGPATH_W) 'readnoaaport.c'; else $(CYGPATH_W) '$(srcdir)/readnoaaport.c'; fi`

readnoaaport-grib2name.o: grib2name.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT readnoaaport-grib2name.o -MD -MP -MF $(DEPDIR)/readnoaaport-grib2name.Tpo -c -o readnoaaport-grib2name.o `test -f 'grib2name.c' || echo '$(srcdir)/'`grib2name.c
	$(am__mv) $(DEPDIR)/readnoaaport-grib2name.Tpo $(DEPDIR)/readnoaaport-grib2name.Po
#	source='grib2name.c' object='readnoaaport-grib2name.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o readnoaaport-grib2name.o `test -f 'grib2name.c' || echo '$(srcdir)/'`grib2name.c

readnoaaport-grib2name.obj: grib2name.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT readnoaaport-grib2name.obj -MD -MP -MF $(DEPDIR)/readnoaaport-grib2name.Tpo -c -o readnoaaport-grib2name.obj `if test -f 'grib2name.c'; then $(CYGPATH_W) 'grib2name.c'; else $(CYGPATH_W) '$(srcdir)/grib2name.c'; fi`
	$(am__mv) $(DEPDIR)/readnoaaport-grib2name.Tpo $(DEPDIR)/readnoaaport-grib2name.Po
#	source='grib2name.c' object='readnoaaport-grib2name.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o readnoaaport-grib2name.obj `if test -f 'grib2name.c'; then $(CYGPATH_W) 'grib2name.c'; else $(CYGPATH_W) '$(srcdir)/grib2name.c'; fi`

readnoaaport-gribid.o: gribid.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT readnoaaport-gribid.o -MD -MP -MF $(DEPDIR)/readnoaaport-gribid.Tpo -c -o readnoaaport-gribid.o `test -f 'gribid.c' || echo '$(srcdir)/'`gribid.c
	$(am__mv) $(DEPDIR)/readnoaaport-gribid.Tpo $(DEPDIR)/readnoaaport-gribid.Po
#	source='gribid.c' object='readnoaaport-gribid.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o readnoaaport-gribid.o `test -f 'gribid.c' || echo '$(srcdir)/'`gribid.c

readnoaaport-gribid.obj: gribid.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT readnoaaport-gribid.obj -MD -MP -MF $(DEPDIR)/readnoaaport-gribid.Tpo -c -o readnoaaport-gribid.obj `if test -f 'gribid.c'; then $(CYGPATH_W) 'gribid.c'; else $(CYGPATH_W) '$(srcdir)/gribid.c'; fi`
	$(am__mv) $(DEPDIR)/readnoaaport-gribid.Tpo $(DEPDIR)/readnoaaport-gribid.Po
#	source='gribid.c' object='readnoaaport-gribid.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o readnoaaport-gribid.obj `if test -f 'gribid.c'; then $(CYGPATH_W) 'gribid.c'; else $(CYGPATH_W) '$(srcdir)/gribid.c'; fi`

readnoaaport-ldmProductQueue.o: ldmProductQueue.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT readnoaaport-ldmProductQueue.o -MD -MP -MF $(DEPDIR)/readnoaaport-ldmProductQueue.Tpo -c -o readnoaaport-ldmProductQueue.o `test -f 'ldmProductQueue.c' || echo '$(srcdir)/'`ldmProductQueue.c
	$(am__mv) $(DEPDIR)/readnoaaport-ldmProductQueue.Tpo $(DEPDIR)/readnoaaport-ldmProductQueue.Po
#	source='ldmProductQueue.c' object='readnoaaport-ldmProductQueue.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o readnoaaport-ldmProductQueue.o `test -f 'ldmProductQueue.c' || echo '$(srcdir)/'`ldmProductQueue.c

readnoaaport-ldmProductQueue.obj: ldmProductQueue.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT readnoaaport-ldmProductQueue.obj -MD -MP -MF $(DEPDIR)/readnoaaport-ldmProductQueue.Tpo -c -o readnoaaport-ldmProductQueue.obj `if test -f 'ldmProductQueue.c'; then $(CYGPATH_W) 'ldmProductQueue.c'; else $(CYGPATH_W) '$(srcdir)/ldmProductQueue.c'; fi`
	$(am__mv) $(DEPDIR)/readnoaaport-ldmProductQueue.Tpo $(DEPDIR)/readnoaaport-ldmProductQueue.Po
#	source='ldmProductQueue.c' object='readnoaaport-ldmProductQueue.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o readnoaaport-ldmProductQueue.obj `if test -f 'ldmProductQueue.c'; then $(CYGPATH_W) 'ldmProductQueue.c'; else $(CYGPATH_W) '$(srcdir)/ldmProductQueue.c'; fi`

readnoaaport-png_io.o: png_io.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT readnoaaport-png_io.o -MD -MP -MF $(DEPDIR)/readnoaaport-png_io.Tpo -c -o readnoaaport-png_io.o `test -f 'png_io.c' || echo '$(srcdir)/'`png_io.c
	$(am__mv) $(DEPDIR)/readnoaaport-png_io.Tpo $(DEPDIR)/readnoaaport-png_io.Po
#	source='png_io.c' object='readnoaaport-png_io.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o readnoaaport-png_io.o `test -f 'png_io.c' || echo '$(srcdir)/'`png_io.c

readnoaaport-png_io.obj: png_io.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT readnoaaport-png_io.obj -MD -MP -MF $(DEPDIR)/readnoaaport-png_io.Tpo -c -o readnoaaport-png_io.obj `if test -f 'png_io.c'; then $(CYGPATH_W) 'png_io.c'; else $(CYGPATH_W) '$(srcdir)/png_io.c'; fi`
	$(am__mv) $(DEPDIR)/readnoaaport-png_io.Tpo $(DEPDIR)/readnoaaport-png_io.Po
#	source='png_io.c' object='readnoaaport-png_io.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o readnoaaport-png_io.obj `if test -f 'png_io.c'; then $(CYGPATH_W) 'png_io.c'; else $(CYGPATH_W) '$(srcdir)/png_io.c'; fi`

readnoaaport-process_prod.o: process_prod.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT readnoaaport-process_prod.o -MD -MP -MF $(DEPDIR)/readnoaaport-process_prod.Tpo -c -o readnoaaport-process_prod.o `test -f 'process_prod.c' || echo '$(srcdir)/'`process_prod.c
	$(am__mv) $(DEPDIR)/readnoaaport-process_prod.Tpo $(DEPDIR)/readnoaaport-process_prod.Po
#	source='process_prod.c' object='readnoaaport-process_prod.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o readnoaaport-process_prod.o `test -f 'process_prod.c' || echo '$(srcdir)/'`process_prod.c

readnoaaport-process_prod.obj: process_prod.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT readnoaaport-process_prod.obj -MD -MP -MF $(DEPDIR)/readnoaaport-process_prod.Tpo -c -o readnoaaport-process_prod.obj `if test -f 'process_prod.c'; then $(CYGPATH_W) 'process_prod.c'; else $(CYGPATH_W) '$(srcdir)/process_prod.c'; fi`
	$(am__mv) $(DEPDIR)/readnoaaport-process_prod.Tpo $(DEPDIR)/readnoaaport-process_prod.Po
#	source='process_prod.c' object='readnoaaport-process_prod.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o readnoaaport-process_prod.obj `if test -f 'process_prod.c'; then $(CYGPATH_W) 'process_prod.c'; else $(CYGPATH_W) '$(srcdir)/process_prod.c'; fi`

readnoaaport-readpdb.o: readpdb.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT readnoaaport-readpdb.o -MD -MP -MF $(DEPDIR)/readnoaaport-readpdb.Tpo -c -o readnoaaport-readpdb.o `test -f 'readpdb.c' || echo '$(srcdir)/'`readpdb.c
	$(am__mv) $(DEPDIR)/readnoaaport-readpdb.Tpo $(DEPDIR)/readnoaaport-readpdb.Po
#	source='readpdb.c' object='readnoaaport-readpdb.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o readnoaaport-readpdb.o `test -f 'readpdb.c' || echo '$(srcdir)/'`readpdb.c

readnoaaport-readpdb.obj: readpdb.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT readnoaaport-readpdb.obj -MD -MP -MF $(DEPDIR)/readnoaaport-readpdb.Tpo -c -o readnoaaport-readpdb.obj `if test -f 'readpdb.c'; then $(CYGPATH_W) 'readpdb.c'; else $(CYGPATH_W) '$(srcdir)/readpdb.c'; fi`
	$(am__mv) $(DEPDIR)/readnoaaport-readpdb.Tpo $(DEPDIR)/readnoaaport-readpdb.Po
#	source='readpdb.c' object='readnoaaport-readpdb.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o readnoaaport-readpdb.obj `if test -f 'readpdb.c'; then $(CYGPATH_W) 'readpdb.c'; else $(CYGPATH_W) '$(srcdir)/readpdb.c'; fi`

readnoaaport-readpdh.o: readpdh.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT readnoaaport-readpdh.o -MD -MP -MF $(DEPDIR)/readnoaaport-readpdh.Tpo -c -o readnoaaport-readpdh.o `test -f 'readpdh.c' || echo '$(srcdir)/'`readpdh.c
	$(am__mv) $(DEPDIR)/readnoaaport-readpdh.Tpo $(DEPDIR)/readnoaaport-readpdh.Po
#	source='readpdh.c' object='readnoaaport-readpdh.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o readnoaaport-readpdh.o `test -f 'readpdh.c' || echo '$(srcdir)/'`readpdh.c

readnoaaport-readpdh.obj: readpdh.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT readnoaaport-readpdh.obj -MD -MP -MF $(DEPDIR)/readnoaaport-readpdh.Tpo -c -o readnoaaport-readpdh.obj `if test -f 'readpdh.c'; then $(CYGPATH_W) 'readpdh.c'; else $(CYGPATH_W) '$(srcdir)/readpdh.c'; fi`
	$(am__mv) $(DEPDIR)/readnoaaport-readpdh.Tpo $(DEPDIR)/readnoaaport-readpdh.Po
#	source='readpdh.c' object='readnoaaport-readpdh.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o readnoaaport-readpdh.obj `if test -f 'readpdh.c'; then $(CYGPATH_W) 'readpdh.c'; else $(CYGPATH_W) '$(srcdir)/readpdh.c'; fi`

readnoaaport-readpsh.o: readpsh.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT readnoaaport-readpsh.o -MD -MP -MF $(DEPDIR)/readnoaaport-readpsh.Tpo -c -o readnoaaport-readpsh.o `test -f 'readpsh.c' || echo '$(srcdir)/'`readpsh.c
	$(am__mv) $(DEPDIR)/readnoaaport-readpsh.Tpo $(DEPDIR)/readnoaaport-readpsh.Po
#	source='readpsh.c' object='readnoaaport-readpsh.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o readnoaaport-readpsh.o `test -f 'readpsh.c' || echo '$(srcdir)/'`readpsh.c

readnoaaport-readpsh.obj: readpsh.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT readnoaaport-readpsh.obj -MD -MP -MF $(DEPDIR)/readnoaaport-readpsh.Tpo -c -o readnoaaport-readpsh.obj `if test -f 'readpsh.c'; then $(CYGPATH_W) 'readpsh.c'; else $(CYGPATH_W) '$(srcdir)/readpsh.c'; fi`
	$(am__mv) $(DEPDIR)/readnoaaport-readpsh.Tpo $(DEPDIR)/readnoaaport-readpsh.Po
#	source='readpsh.c' object='readnoaaport-readpsh.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o readnoaaport-readpsh.obj `if test -f 'readpsh.c'; then $(CYGPATH_W) 'readpsh.c'; else $(CYGPATH_W) '$(srcdir)/readpsh.c'; fi`

readnoaaport-readsbn.o: readsbn.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT readnoaaport-readsbn.o -MD -MP -MF $(DEPDIR)/readnoaaport-readsbn.Tpo -c -o readnoaaport-readsbn.o `test -f 'readsbn.c' || echo '$(srcdir)/'`readsbn.c
	$(am__mv) $(DEPDIR)/readnoaaport-readsbn.Tpo $(DEPDIR)/readnoaaport-readsbn.Po
#	source='readsbn.c' object='readnoaaport-readsbn.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o readnoaaport-readsbn.o `test -f 'readsbn.c' || echo '$(srcdir)/'`readsbn.c

readnoaaport-readsbn.obj: readsbn.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT readnoaaport-readsbn.obj -MD -MP -MF $(DEPDIR)/readnoaaport-readsbn.Tpo -c -o readnoaaport-readsbn.obj `if test -f 'readsbn.c'; then $(CYGPATH_W) 'readsbn.c'; else $(CYGPATH_W) '$(srcdir)/readsbn.c'; fi`
	$(am__mv) $(DEPDIR)/readnoaaport-readsbn.Tpo $(DEPDIR)/readnoaaport-readsbn.Po
#	source='readsbn.c' object='readnoaaport-readsbn.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o readnoaaport-readsbn.obj `if test -f 'readsbn.c'; then $(CYGPATH_W) 'readsbn.c'; else $(CYGPATH_W) '$(srcdir)/readsbn.c'; fi`

readnoaaport-redbook_header.o: redbook_header.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT readnoaaport-redbook_header.o -MD -MP -MF $(DEPDIR)/readnoaaport-redbook_header.Tpo -c -o readnoaaport-redbook_header.o `test -f 'redbook_header.c' || echo '$(srcdir)/'`redbook_header.c
	$(am__mv) $(DEPDIR)/readnoaaport-redbook_header.Tpo $(DEPDIR)/readnoaaport-redbook_header.Po
#	source='redbook_header.c' object='readnoaaport-redbook_header.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o readnoaaport-redbook_header.o `test -f 'redbook_header.c' || echo '$(srcdir)/'`redbook_header.c

readnoaaport-redbook_header.obj: redbook_header.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT readnoaaport-redbook_header.obj -MD -MP -MF $(DEPDIR)/readnoaaport-redbook_header.Tpo -c -o readnoaaport-redbook_header.obj `if test -f 'redbook_header.c'; then $(CYGPATH_W) 'redbook_header.c'; else $(CYGPATH_W) '$(srcdir)/redbook_header.c'; fi`
	$(am__mv) $(DEPDIR)/readnoaaport-redbook_header.Tpo $(DEPDIR)/readnoaaport-redbook_header.Po
#	source='redbook_header.c' object='readnoaaport-redbook_header.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o readnoaaport-redbook_header.obj `if test -f 'redbook_header.c'; then $(CYGPATH_W) 'redbook_header.c'; else $(CYGPATH_W) '$(srcdir)/redbook_header.c'; fi`

readnoaaport-wgrib.o: wgrib.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT readnoaaport-wgrib.o -MD -MP -MF $(DEPDIR)/readnoaaport-wgrib.Tpo -c -o readnoaaport-wgrib.o `test -f 'wgrib.c' || echo '$(srcdir)/'`wgrib.c
	$(am__mv) $(DEPDIR)/readnoaaport-wgrib.Tpo $(DEPDIR)/readnoaaport-wgrib.Po
#	source='wgrib.c' object='readnoaaport-wgrib.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o readnoaaport-wgrib.o `test -f 'wgrib.c' || echo '$(srcdir)/'`wgrib.c

readnoaaport-wgrib.obj: wgrib.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT readnoaaport-wgrib.obj -MD -MP -MF $(DEPDIR)/readnoaaport-wgrib.Tpo -c -o readnoaaport-wgrib.obj `if test -f 'wgrib.c'; then $(CYGPATH_W) 'wgrib.c'; else $(CYGPATH_W) '$(srcdir)/wgrib.c'; fi`
	$(am__mv) $(DEPDIR)/readnoaaport-wgrib.Tpo $(DEPDIR)/readnoaaport-wgrib.Po
#	source='wgrib.c' object='readnoaaport-wgrib.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o readnoaaport-wgrib.obj `if test -f 'wgrib.c'; then $(CYGPATH_W) 'wgrib.c'; else $(CYGPATH_W) '$(srcdir)/wgrib.c'; fi`

readnoaaport-wmo_header.o: wmo_header.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT readnoaaport-wmo_header.o -MD -MP -MF $(DEPDIR)/readnoaaport-wmo_header.Tpo -c -o readnoaaport-wmo_header.o `test -f 'wmo_header.c' || echo '$(srcdir)/'`wmo_header.c
	$(am__mv) $(DEPDIR)/readnoaaport-wmo_header.Tpo $(DEPDIR)/readnoaaport-wmo_header.Po
#	source='wmo_header.c' object='readnoaaport-wmo_header.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o readnoaaport-wmo_header.o `test -f 'wmo_header.c' || echo '$(srcdir)/'`wmo_header.c

readnoaaport-wmo_header.obj: wmo_header.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT readnoaaport-wmo_header.obj -MD -MP -MF $(DEPDIR)/readnoaaport-wmo_header.Tpo -c -o readnoaaport-wmo_header.obj `if test -f 'wmo_header.c'; then $(CYGPATH_W) 'wmo_header.c'; else $(CYGPATH_W) '$(srcdir)/wmo_header.c'; fi`
	$(am__mv) $(DEPDIR)/readnoaaport-wmo_header.Tpo $(DEPDIR)/readnoaaport-wmo_header.Po
#	source='wmo_header.c' object='readnoaaport-wmo_header.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(readnoaaport_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o readnoaaport-wmo_header.obj `if test -f 'wmo_header.c'; then $(CYGPATH_W) 'wmo_header.c'; else $(CYGPATH_W) '$(srcdir)/wmo_header.c'; fi`

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool config.lt

# This directory's subdirectories are mostly independent; you can cd
# into them and run `make' without going through this Makefile.
# To change the values of `make' variables: instead of editing Makefiles,
# (1) if the variable is set in `config.status', edit `config.status'
#     (which will cause the Makefiles to be regenerated when you run `make');
# (2) otherwise, pass the desired values on the `make' command line.
$(RECURSIVE_TARGETS):
	@failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

$(RECURSIVE_CLEAN_TARGETS):
	@failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	rev=''; for subdir in $$list; do \
	  if test "$$subdir" = "."; then :; else \
	    rev="$$subdir $$rev"; \
	  fi; \
	done; \
	rev="$$rev ."; \
	target=`echo $@ | sed s/-recursive//`; \
	for subdir in $$rev; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done && test -z "$$fail"
tags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) tags); \
	done
ctags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) ctags); \
	done

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS: tags-recursive $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      set "$$@" "$$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS: ctags-recursive $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test -d "$(distdir)/$$subdir" \
	    || $(MKDIR_P) "$(distdir)/$$subdir" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    dir1=$$subdir; dir2="$(distdir)/$$subdir"; \
	    $(am__relativize); \
	    new_distdir=$$reldir; \
	    dir1=$$subdir; dir2="$(top_distdir)"; \
	    $(am__relativize); \
	    new_top_distdir=$$reldir; \
	    echo " (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) top_distdir="$$new_top_distdir" distdir="$$new_distdir" \\"; \
	    echo "     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)"; \
	    ($(am__cd) $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$new_top_distdir" \
	        distdir="$$new_distdir" \
		am__remove_distdir=: \
		am__skip_length_check=: \
		am__skip_mode_fix=: \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -777 -exec chmod a+rwx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bunzip2 -c $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  unlzma -c $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@$(am__cd) '$(distuninstallcheck_dir)' \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
	$(MAKE) $(AM_MAKEFLAGS) check-local
check: check-recursive
all-am: Makefile $(LTLIBRARIES) $(PROGRAMS) $(SCRIPTS) config.h
install-binPROGRAMS: install-libLTLIBRARIES

installdirs: installdirs-recursive
installdirs-am:
	for dir in "$(DESTDIR)$(libdir)" "$(DESTDIR)$(bindir)" "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-test -z "$(DISTCLEANFILES)" || rm -f $(DISTCLEANFILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-recursive

clean-am: clean-binPROGRAMS clean-generic clean-libLTLIBRARIES \
	clean-libtool mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

html-am:

info: info-recursive

info-am:

install-data-am:
	@$(NORMAL_INSTALL)
	$(MAKE) $(AM_MAKEFLAGS) install-data-hook
install-dvi: install-dvi-recursive

install-dvi-am:

install-exec-am: install-binPROGRAMS install-dist_binSCRIPTS \
	install-libLTLIBRARIES
	@$(NORMAL_INSTALL)
	$(MAKE) $(AM_MAKEFLAGS) install-exec-hook
install-html-am:

install-info: install-info-recursive

install-info-am:

install-man:

install-pdf: install-pdf-recursive

install-pdf-am:

install-ps: install-ps-recursive

install-ps-am:

installcheck-am: installcheck-local

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-dist_binSCRIPTS \
	uninstall-libLTLIBRARIES
	@$(NORMAL_INSTALL)
	$(MAKE) $(AM_MAKEFLAGS) uninstall-hook
.MAKE: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) all check-am \
	ctags-recursive install-am install-data-am install-exec-am \
	install-strip tags-recursive uninstall-am

.PHONY: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) CTAGS GTAGS \
	all all-am am--refresh check check-am check-local clean \
	clean-binPROGRAMS clean-generic clean-libLTLIBRARIES \
	clean-libtool ctags ctags-recursive dist dist-all dist-bzip2 \
	dist-gzip dist-lzma dist-shar dist-tarZ dist-xz dist-zip \
	distcheck distclean distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags distcleancheck \
	distdir distuninstallcheck dvi dvi-am html html-am info \
	info-am install install-am install-binPROGRAMS install-data \
	install-data-am install-data-hook install-dist_binSCRIPTS \
	install-dvi install-dvi-am install-exec install-exec-am \
	install-exec-hook install-html install-html-am install-info \
	install-info-am install-libLTLIBRARIES install-man install-pdf \
	install-pdf-am install-ps install-ps-am install-strip \
	installcheck installcheck-am installcheck-local installdirs \
	installdirs-am maintainer-clean maintainer-clean-generic \
	mostlyclean mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool pdf pdf-am ps ps-am tags tags-recursive \
	uninstall uninstall-am uninstall-binPROGRAMS \
	uninstall-dist_binSCRIPTS uninstall-hook \
	uninstall-libLTLIBRARIES


all:		$(srcdir)/html/index.html

$(srcdir)/html/index.html:	$(srcdir)/configure.ac $(srcdir)/mainpage.h.in \
		$(srcdir)/Doxyfile
	cd $(srcdir) && doxygen Doxyfile

.hin.h:
	./extractDecls $*.hin $*.c >$@.tmp
	mv -f $@.tmp $@
shmfifo.h:		shmfifo.c shmfifo.hin extractDecls
ldmProductQueue.h:	ldmProductQueue.c ldmProductQueue.hin extractDecls
fifo.h:			fifo.c fifo.hin extractDecls
reader.h:		reader.c reader.hin extractDecls
fileReader.h:		fileReader.c fileReader.hin extractDecls
multicastReader.h:	multicastReader.c multicastReader.hin extractDecls
productMaker.h:		productMaker.c productMaker.hin extractDecls
getFacilityName.h:	getFacilityName.c getFacilityName.hin extractDecls

.c.i:
	$(CC) $(CPPFLAGS) -E $< >$@

libpng/libpng.la:
	cd libpng && $(MAKE) $(AM_MAKEFLAGS) all

install-exec-hook:
	@echo
	@echo "\
The next step will perform those installation actions that must be executed \
by the superuser. \
If this step doesn't work (for example, if you don't enter \
root's password), then the superuser will have to manually execute the \
command \"$(MAKE) root-actions\"." \
	| fmt >/dev/tty
	@echo >/dev/tty
#	$(SUDO) $(MAKE) $(AM_MAKEFLAGS) root-actions 2>/dev/tty
	@printf "Enter root's password (or don't): " >/dev/tty
	@$(SU) root -c 'PATH='$$PATH' $(MAKE) $(AM_MAKEFLAGS) root-actions' \
	    </dev/tty 2>/dev/tty
	@echo >/dev/tty
#	@echo
#	@echo "\
#NOTE: The command \"$(MAKE) root-actions\" will have to be executed by the \
#superuser in order to complete the installation process." \
#	| fmt
#	@echo

root-actions:		install_setuids

install_setuids:
	chown root $(DESTDIR)$(bindir)/dvbs_multicast
	chmod 4755 $(DESTDIR)$(bindir)/dvbs_multicast
	@if ls -l $(bindir)/dvbs_multicast | grep root >/dev/null; then \
	    : true; \
	else \
	    echo; \
	    echo "\
ERROR: The program (../bin/dvbs_multicast) is not owned by \"root\" or does \
not have the setuid bit enabled.  The command \"make install_setuids\" will \
have to be manually executed by the superuser on a system that allows these \
actions." \
	    | fmt; \
	    echo; \
	    exit 1; \
	fi

installcheck-local:
	pqcreate -c -s 2m /tmp/readnoaaport-test.pq
	$(DESTDIR)$(bindir)/readnoaaport -l- -q /tmp/readnoaaport-test.pq \
	    $(srcdir)/nwstgdump.data
	rm /tmp/readnoaaport-test.pq

check-local:		check-readnoaaport check-noaaportIngester
check-readnoaaport:	readnoaaport
	pqcreate -c -s 2m /tmp/readnoaaport-test.pq
	./readnoaaport -nl- -q /tmp/readnoaaport-test.pq \
	    $(srcdir)/nwstgdump.data
	rm /tmp/readnoaaport-test.pq
check-noaaportIngester:	noaaportIngester
	pqcreate -c -s 2m /tmp/noaaportIngester-test.pq
	./noaaportIngester -n -q /tmp/noaaportIngester-test.pq \
	    <$(srcdir)/nwstgdump.data
	rm /tmp/noaaportIngester-test.pq

valgrind:		valgrind-readnoaaport valgrind-noaaportIngester

valgrind-readnoaaport:		readnoaaport
	pqcreate -c -s 2m /tmp/readnoaaport-test.pq
	$(LIBTOOL) --mode=execute valgrind --leak-check=yes \
	    readnoaaport -l- -q /tmp/readnoaaport-test.pq nwstgdump.data
	rm /tmp/readnoaaport-test.pq

valgrind-noaaportIngester:		noaaportIngester
	pqcreate -c -s 2m /tmp/noaaportIngester-test.pq
	$(LIBTOOL) --mode=execute valgrind --leak-check=yes \
	    noaaportIngester -n -q /tmp/noaaportIngester-test.pq \
		<$(srcdir)/nwstgdump.data
	rm /tmp/noaaportIngester-test.pq

debug-readnoaaport:	readnoaaport
	pqcreate -c -s 2m /tmp/readnoaaport-test.pq
	echo 'handle SIGCONT pass noprint nostop' >/tmp/readnoaaport.gdb
	echo 'b 617' >>/tmp/readnoaaport.gdb
	echo 'run -l- -q /tmp/readnoaaport-test.pq nwstgdump.data' \
	    >>/tmp/readnoaaport.gdb
	$(LIBTOOL) --mode=execute gdb -x /tmp/readnoaaport.gdb readnoaaport
	rm /tmp/readnoaaport-test.pq /tmp/readnoaaport.gdb

debug-noaaportIngester:	noaaportIngester
	pqcreate -c -s 2m /tmp/noaaportIngester-test.pq
	echo 'handle SIGCONT pass noprint nostop' >/tmp/noaaportIngester.gdb
	echo 'handle SIGTERM pass nostop' >/tmp/noaaportIngester.gdb
	echo 'run -q /tmp/noaaportIngester-test.pq -n -m 224.0.1.1' \
	    >>/tmp/noaaportIngester.gdb
	$(LIBTOOL) --mode=execute gdb -x /tmp/noaaportIngester.gdb \
	      noaaportIngester
	rm /tmp/noaaportIngester-test.pq /tmp/noaaportIngester.gdb

install-html:		$(srcdir)/html/index.html $(DESTDIR)$(htmldir)
	cp -R $(srcdir)/html/* $(DESTDIR)$(htmldir)

$(DESTDIR)$(htmldir):
	mkdir -p $@

install-data-hook:	install-html

uninstall-hook:
	chmod -R +w $(DESTDIR)$(htmldir)
	rm -rf $(DESTDIR)$(htmldir)

$(FTPDIR) \
$(WEBROOT):
	mkdir -p $@

releaseCheck:
	git diff `git tag -l v\* | tail -1` >diff.log
	if ! test -s diff.log; then \
	    echo 2>&1 "No changes since last release!"; \
	    rm diff.log; \
	    exit 1; \
	fi
	rm diff.log
	regex=`echo $(VERSION) | sed 's/\./\\./g'`; \
	if git tag -l v\* | grep "^v$$regex$$"; then \
	    echo 2>&1 'Tag "v$(VERSION)" already exists!'; \
	    exit 1; \
	fi

timestamp:
	awk 'NR == 1 {\
		print $$1, "	'"`date --rfc-3339=seconds`"'";\
		next;\
	    }\
	    {print}' CHANGE_LOG >CHANGE_LOG.tmp
	mv CHANGE_LOG.tmp CHANGE_LOG

dist:		configure $(srcdir)/html/index.html

commitAndTag:
	git commit -a -m "v$(VERSION)"
	git tag -f "v$(VERSION)"

release:	releaseCheck
	-git commit -a
	echo 'PUT VERSION HERE' >CHANGE_LOG.tmp
	git log --pretty=full `git tag -l v\* | tail -1`.. >>CHANGE_LOG.tmp
	echo '' >>CHANGE_LOG.tmp
	cat CHANGE_LOG >>CHANGE_LOG.tmp
	vi CHANGE_LOG.tmp
	mv CHANGE_LOG.tmp CHANGE_LOG
	@newVersion=`awk '{print $$1; exit}' CHANGE_LOG`; \
	echo $$newVersion | egrep '^[0-9]+(\.[0-9]+)*$$' >/dev/null || exit 1; \
	sed '/^AC_INIT(/s/[0-9][0-9.]*,/'"$$newVersion"',/' configure.ac \
	    >configure.ac.tmp
	mv configure.ac.tmp configure.ac
	$(MAKE) timestamp dist commitAndTag

ensureRelease:
	-@$(MAKE) release

ftp-actual:		dist $(FTPDIR)
	cp $(distArchive) $(FTPDIR)
	chmod u+rw,g+rw,o=r $(FTPDIR)/$(distArchive)
	rm -f $(FTPDIR)/$(PACKAGE).tar.gz
	$(LN_S) $(distArchive) $(FTPDIR)/$(PACKAGE).tar.gz

ftp:			ensureRelease
	$(MAKE) ftp-actual

software-update:	$(srcdir)/html/index.html $(WEBROOT)
	-mkdir $(WEBROOT)/$(VERSION)
	cp -R html/* $(WEBROOT)/$(VERSION)
	echo 'RemoveOutputFilter LAYOUT html htm' \
	    >$(WEBROOT)/$(VERSION)/.htaccess
	rm -f $(WEBROOT)/current
	$(LN_S) $(VERSION) $(WEBROOT)/current

download_update:
	previous=`sed -n 's/.*"%current%" value="\(.*\)".*/\1/p' \
		 /web/content/downloads/$(PACKAGE)/toc.xml`; \
	if test "$$previous" != "$(VERSION)"; then \
	    sed -e 's/"%current%" value=".*"/"%current%" value="$(VERSION)"/' \
	    -e 's/"%previous%" value=".*"/"%previous%" value="'$$previous'"/' \
		/web/content/downloads/$(PACKAGE)/toc.xml >toc.xml.new; \
	    cp /web/content/downloads/$(PACKAGE)/toc.xml \
		/web/content/downloads/$(PACKAGE)/toc.xml.old; \
	    mv -f toc.xml.new /web/content/downloads/$(PACKAGE)/toc.xml; \
	fi

web-update:		ensureRelease
	$(MAKE) software-update download_update

# Apparently, there's no rule to create $(distArchive).
available:		ensureRelease
	$(MAKE) $(distArchive) ftp web-update

.PHONY:	\
	available \
	commitAndTag \
	download_update \
	ensureRelease \
	ftp \
	ftp-actual \
	install-html \
	release \
	releaseCheck \
	software-update \
	timestamp \
	web-update

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
